// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/iris-api/models"
)

// NewCreateDNSZoneRecordParams creates a new CreateDNSZoneRecordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDNSZoneRecordParams() *CreateDNSZoneRecordParams {
	return &CreateDNSZoneRecordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDNSZoneRecordParamsWithTimeout creates a new CreateDNSZoneRecordParams object
// with the ability to set a timeout on a request.
func NewCreateDNSZoneRecordParamsWithTimeout(timeout time.Duration) *CreateDNSZoneRecordParams {
	return &CreateDNSZoneRecordParams{
		timeout: timeout,
	}
}

// NewCreateDNSZoneRecordParamsWithContext creates a new CreateDNSZoneRecordParams object
// with the ability to set a context for a request.
func NewCreateDNSZoneRecordParamsWithContext(ctx context.Context) *CreateDNSZoneRecordParams {
	return &CreateDNSZoneRecordParams{
		Context: ctx,
	}
}

// NewCreateDNSZoneRecordParamsWithHTTPClient creates a new CreateDNSZoneRecordParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDNSZoneRecordParamsWithHTTPClient(client *http.Client) *CreateDNSZoneRecordParams {
	return &CreateDNSZoneRecordParams{
		HTTPClient: client,
	}
}

/*
CreateDNSZoneRecordParams contains all the parameters to send to the API endpoint

	for the create DNS zone record operation.

	Typically these are written to a http.Request.
*/
type CreateDNSZoneRecordParams struct {

	// Body.
	Body *models.Record

	/* ZoneID.

	   The ID of the DNS zone to create record on.
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDNSZoneRecordParams) WithDefaults() *CreateDNSZoneRecordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDNSZoneRecordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) WithTimeout(timeout time.Duration) *CreateDNSZoneRecordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) WithContext(ctx context.Context) *CreateDNSZoneRecordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) WithHTTPClient(client *http.Client) *CreateDNSZoneRecordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) WithBody(body *models.Record) *CreateDNSZoneRecordParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) SetBody(body *models.Record) {
	o.Body = body
}

// WithZoneID adds the zoneID to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) WithZoneID(zoneID string) *CreateDNSZoneRecordParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the create DNS zone record params
func (o *CreateDNSZoneRecordParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDNSZoneRecordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param zoneId
	if err := r.SetPathParam("zoneId", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
