// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/iris-api/models"
)

// NewCreateDNSZoneParams creates a new CreateDNSZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDNSZoneParams() *CreateDNSZoneParams {
	return &CreateDNSZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDNSZoneParamsWithTimeout creates a new CreateDNSZoneParams object
// with the ability to set a timeout on a request.
func NewCreateDNSZoneParamsWithTimeout(timeout time.Duration) *CreateDNSZoneParams {
	return &CreateDNSZoneParams{
		timeout: timeout,
	}
}

// NewCreateDNSZoneParamsWithContext creates a new CreateDNSZoneParams object
// with the ability to set a context for a request.
func NewCreateDNSZoneParamsWithContext(ctx context.Context) *CreateDNSZoneParams {
	return &CreateDNSZoneParams{
		Context: ctx,
	}
}

// NewCreateDNSZoneParamsWithHTTPClient creates a new CreateDNSZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDNSZoneParamsWithHTTPClient(client *http.Client) *CreateDNSZoneParams {
	return &CreateDNSZoneParams{
		HTTPClient: client,
	}
}

/*
CreateDNSZoneParams contains all the parameters to send to the API endpoint

	for the create DNS zone operation.

	Typically these are written to a http.Request.
*/
type CreateDNSZoneParams struct {

	// Body.
	Body *models.Zone

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create DNS zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDNSZoneParams) WithDefaults() *CreateDNSZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create DNS zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDNSZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create DNS zone params
func (o *CreateDNSZoneParams) WithTimeout(timeout time.Duration) *CreateDNSZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create DNS zone params
func (o *CreateDNSZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create DNS zone params
func (o *CreateDNSZoneParams) WithContext(ctx context.Context) *CreateDNSZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create DNS zone params
func (o *CreateDNSZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create DNS zone params
func (o *CreateDNSZoneParams) WithHTTPClient(client *http.Client) *CreateDNSZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create DNS zone params
func (o *CreateDNSZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create DNS zone params
func (o *CreateDNSZoneParams) WithBody(body *models.Zone) *CreateDNSZoneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create DNS zone params
func (o *CreateDNSZoneParams) SetBody(body *models.Zone) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDNSZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
