// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDNSZoneRecordParams creates a new DeleteDNSZoneRecordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDNSZoneRecordParams() *DeleteDNSZoneRecordParams {
	return &DeleteDNSZoneRecordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDNSZoneRecordParamsWithTimeout creates a new DeleteDNSZoneRecordParams object
// with the ability to set a timeout on a request.
func NewDeleteDNSZoneRecordParamsWithTimeout(timeout time.Duration) *DeleteDNSZoneRecordParams {
	return &DeleteDNSZoneRecordParams{
		timeout: timeout,
	}
}

// NewDeleteDNSZoneRecordParamsWithContext creates a new DeleteDNSZoneRecordParams object
// with the ability to set a context for a request.
func NewDeleteDNSZoneRecordParamsWithContext(ctx context.Context) *DeleteDNSZoneRecordParams {
	return &DeleteDNSZoneRecordParams{
		Context: ctx,
	}
}

// NewDeleteDNSZoneRecordParamsWithHTTPClient creates a new DeleteDNSZoneRecordParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDNSZoneRecordParamsWithHTTPClient(client *http.Client) *DeleteDNSZoneRecordParams {
	return &DeleteDNSZoneRecordParams{
		HTTPClient: client,
	}
}

/*
DeleteDNSZoneRecordParams contains all the parameters to send to the API endpoint

	for the delete DNS zone record operation.

	Typically these are written to a http.Request.
*/
type DeleteDNSZoneRecordParams struct {

	/* RecordID.

	   The ID of the DNS record to delete.
	*/
	RecordID string

	/* Type.

	   The DNS record types to be removed.
	*/
	Type string

	/* ZoneID.

	   The ID of the zone's record to delete.
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDNSZoneRecordParams) WithDefaults() *DeleteDNSZoneRecordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDNSZoneRecordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithTimeout(timeout time.Duration) *DeleteDNSZoneRecordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithContext(ctx context.Context) *DeleteDNSZoneRecordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithHTTPClient(client *http.Client) *DeleteDNSZoneRecordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordID adds the recordID to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithRecordID(recordID string) *DeleteDNSZoneRecordParams {
	o.SetRecordID(recordID)
	return o
}

// SetRecordID adds the recordId to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetRecordID(recordID string) {
	o.RecordID = recordID
}

// WithType adds the typeVar to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithType(typeVar string) *DeleteDNSZoneRecordParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WithZoneID adds the zoneID to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) WithZoneID(zoneID string) *DeleteDNSZoneRecordParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the delete DNS zone record params
func (o *DeleteDNSZoneRecordParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDNSZoneRecordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recordId
	if err := r.SetPathParam("recordId", o.RecordID); err != nil {
		return err
	}

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {

		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	// path param zoneId
	if err := r.SetPathParam("zoneId", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
