// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDisableDNSZoneRecordParams creates a new DisableDNSZoneRecordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDisableDNSZoneRecordParams() *DisableDNSZoneRecordParams {
	return &DisableDNSZoneRecordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDisableDNSZoneRecordParamsWithTimeout creates a new DisableDNSZoneRecordParams object
// with the ability to set a timeout on a request.
func NewDisableDNSZoneRecordParamsWithTimeout(timeout time.Duration) *DisableDNSZoneRecordParams {
	return &DisableDNSZoneRecordParams{
		timeout: timeout,
	}
}

// NewDisableDNSZoneRecordParamsWithContext creates a new DisableDNSZoneRecordParams object
// with the ability to set a context for a request.
func NewDisableDNSZoneRecordParamsWithContext(ctx context.Context) *DisableDNSZoneRecordParams {
	return &DisableDNSZoneRecordParams{
		Context: ctx,
	}
}

// NewDisableDNSZoneRecordParamsWithHTTPClient creates a new DisableDNSZoneRecordParams object
// with the ability to set a custom HTTPClient for a request.
func NewDisableDNSZoneRecordParamsWithHTTPClient(client *http.Client) *DisableDNSZoneRecordParams {
	return &DisableDNSZoneRecordParams{
		HTTPClient: client,
	}
}

/*
DisableDNSZoneRecordParams contains all the parameters to send to the API endpoint

	for the disable DNS zone record operation.

	Typically these are written to a http.Request.
*/
type DisableDNSZoneRecordParams struct {

	/* RecordID.

	   The ID of the DNS record to disable.
	*/
	RecordID string

	/* ZoneID.

	   The ID of the zone's record to disable.
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the disable DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableDNSZoneRecordParams) WithDefaults() *DisableDNSZoneRecordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the disable DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableDNSZoneRecordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) WithTimeout(timeout time.Duration) *DisableDNSZoneRecordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) WithContext(ctx context.Context) *DisableDNSZoneRecordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) WithHTTPClient(client *http.Client) *DisableDNSZoneRecordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordID adds the recordID to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) WithRecordID(recordID string) *DisableDNSZoneRecordParams {
	o.SetRecordID(recordID)
	return o
}

// SetRecordID adds the recordId to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) SetRecordID(recordID string) {
	o.RecordID = recordID
}

// WithZoneID adds the zoneID to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) WithZoneID(zoneID string) *DisableDNSZoneRecordParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the disable DNS zone record params
func (o *DisableDNSZoneRecordParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *DisableDNSZoneRecordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recordId
	if err := r.SetPathParam("recordId", o.RecordID); err != nil {
		return err
	}

	// path param zoneId
	if err := r.SetPathParam("zoneId", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
