// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllDNSServersParams creates a new GetAllDNSServersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllDNSServersParams() *GetAllDNSServersParams {
	return &GetAllDNSServersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllDNSServersParamsWithTimeout creates a new GetAllDNSServersParams object
// with the ability to set a timeout on a request.
func NewGetAllDNSServersParamsWithTimeout(timeout time.Duration) *GetAllDNSServersParams {
	return &GetAllDNSServersParams{
		timeout: timeout,
	}
}

// NewGetAllDNSServersParamsWithContext creates a new GetAllDNSServersParams object
// with the ability to set a context for a request.
func NewGetAllDNSServersParamsWithContext(ctx context.Context) *GetAllDNSServersParams {
	return &GetAllDNSServersParams{
		Context: ctx,
	}
}

// NewGetAllDNSServersParamsWithHTTPClient creates a new GetAllDNSServersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllDNSServersParamsWithHTTPClient(client *http.Client) *GetAllDNSServersParams {
	return &GetAllDNSServersParams{
		HTTPClient: client,
	}
}

/*
GetAllDNSServersParams contains all the parameters to send to the API endpoint

	for the get all DNS servers operation.

	Typically these are written to a http.Request.
*/
type GetAllDNSServersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all DNS servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDNSServersParams) WithDefaults() *GetAllDNSServersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all DNS servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllDNSServersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all DNS servers params
func (o *GetAllDNSServersParams) WithTimeout(timeout time.Duration) *GetAllDNSServersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all DNS servers params
func (o *GetAllDNSServersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all DNS servers params
func (o *GetAllDNSServersParams) WithContext(ctx context.Context) *GetAllDNSServersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all DNS servers params
func (o *GetAllDNSServersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all DNS servers params
func (o *GetAllDNSServersParams) WithHTTPClient(client *http.Client) *GetAllDNSServersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all DNS servers params
func (o *GetAllDNSServersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllDNSServersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
