// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDNSZoneRecordParams creates a new GetDNSZoneRecordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDNSZoneRecordParams() *GetDNSZoneRecordParams {
	return &GetDNSZoneRecordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDNSZoneRecordParamsWithTimeout creates a new GetDNSZoneRecordParams object
// with the ability to set a timeout on a request.
func NewGetDNSZoneRecordParamsWithTimeout(timeout time.Duration) *GetDNSZoneRecordParams {
	return &GetDNSZoneRecordParams{
		timeout: timeout,
	}
}

// NewGetDNSZoneRecordParamsWithContext creates a new GetDNSZoneRecordParams object
// with the ability to set a context for a request.
func NewGetDNSZoneRecordParamsWithContext(ctx context.Context) *GetDNSZoneRecordParams {
	return &GetDNSZoneRecordParams{
		Context: ctx,
	}
}

// NewGetDNSZoneRecordParamsWithHTTPClient creates a new GetDNSZoneRecordParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDNSZoneRecordParamsWithHTTPClient(client *http.Client) *GetDNSZoneRecordParams {
	return &GetDNSZoneRecordParams{
		HTTPClient: client,
	}
}

/*
GetDNSZoneRecordParams contains all the parameters to send to the API endpoint

	for the get DNS zone record operation.

	Typically these are written to a http.Request.
*/
type GetDNSZoneRecordParams struct {

	/* RecordID.

	   The ID of the DNS record to query.
	*/
	RecordID string

	/* ZoneID.

	   The ID of the DNS zone to query.
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSZoneRecordParams) WithDefaults() *GetDNSZoneRecordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get DNS zone record params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSZoneRecordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get DNS zone record params
func (o *GetDNSZoneRecordParams) WithTimeout(timeout time.Duration) *GetDNSZoneRecordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get DNS zone record params
func (o *GetDNSZoneRecordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get DNS zone record params
func (o *GetDNSZoneRecordParams) WithContext(ctx context.Context) *GetDNSZoneRecordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get DNS zone record params
func (o *GetDNSZoneRecordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get DNS zone record params
func (o *GetDNSZoneRecordParams) WithHTTPClient(client *http.Client) *GetDNSZoneRecordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get DNS zone record params
func (o *GetDNSZoneRecordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordID adds the recordID to the get DNS zone record params
func (o *GetDNSZoneRecordParams) WithRecordID(recordID string) *GetDNSZoneRecordParams {
	o.SetRecordID(recordID)
	return o
}

// SetRecordID adds the recordId to the get DNS zone record params
func (o *GetDNSZoneRecordParams) SetRecordID(recordID string) {
	o.RecordID = recordID
}

// WithZoneID adds the zoneID to the get DNS zone record params
func (o *GetDNSZoneRecordParams) WithZoneID(zoneID string) *GetDNSZoneRecordParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the get DNS zone record params
func (o *GetDNSZoneRecordParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDNSZoneRecordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recordId
	if err := r.SetPathParam("recordId", o.RecordID); err != nil {
		return err
	}

	// path param zoneId
	if err := r.SetPathParam("zoneId", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
