// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAllDNSZonesReader is a Reader for the GetAllDNSZones structure.
type GetAllDNSZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllDNSZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllDNSZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllDNSZonesOK creates a GetAllDNSZonesOK with default headers values
func NewGetAllDNSZonesOK() *GetAllDNSZonesOK {
	return &GetAllDNSZonesOK{}
}

/*
GetAllDNSZonesOK describes a response with status code 200, with default header values.

Returns the an array of DNS zones.
*/
type GetAllDNSZonesOK struct {
	Payload []string
}

// IsSuccess returns true when this get all Dns zones o k response has a 2xx status code
func (o *GetAllDNSZonesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all Dns zones o k response has a 3xx status code
func (o *GetAllDNSZonesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all Dns zones o k response has a 4xx status code
func (o *GetAllDNSZonesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all Dns zones o k response has a 5xx status code
func (o *GetAllDNSZonesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all Dns zones o k response a status code equal to that given
func (o *GetAllDNSZonesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all Dns zones o k response
func (o *GetAllDNSZonesOK) Code() int {
	return 200
}

func (o *GetAllDNSZonesOK) Error() string {
	return fmt.Sprintf("[GET /dns/zone][%d] getAllDnsZonesOK  %+v", 200, o.Payload)
}

func (o *GetAllDNSZonesOK) String() string {
	return fmt.Sprintf("[GET /dns/zone][%d] getAllDnsZonesOK  %+v", 200, o.Payload)
}

func (o *GetAllDNSZonesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAllDNSZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
