// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDNSServerParams creates a new GetDNSServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDNSServerParams() *GetDNSServerParams {
	return &GetDNSServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDNSServerParamsWithTimeout creates a new GetDNSServerParams object
// with the ability to set a timeout on a request.
func NewGetDNSServerParamsWithTimeout(timeout time.Duration) *GetDNSServerParams {
	return &GetDNSServerParams{
		timeout: timeout,
	}
}

// NewGetDNSServerParamsWithContext creates a new GetDNSServerParams object
// with the ability to set a context for a request.
func NewGetDNSServerParamsWithContext(ctx context.Context) *GetDNSServerParams {
	return &GetDNSServerParams{
		Context: ctx,
	}
}

// NewGetDNSServerParamsWithHTTPClient creates a new GetDNSServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDNSServerParamsWithHTTPClient(client *http.Client) *GetDNSServerParams {
	return &GetDNSServerParams{
		HTTPClient: client,
	}
}

/*
GetDNSServerParams contains all the parameters to send to the API endpoint

	for the get DNS server operation.

	Typically these are written to a http.Request.
*/
type GetDNSServerParams struct {

	/* ServerID.

	   The ID of the DNS server to query.
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get DNS server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSServerParams) WithDefaults() *GetDNSServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get DNS server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get DNS server params
func (o *GetDNSServerParams) WithTimeout(timeout time.Duration) *GetDNSServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get DNS server params
func (o *GetDNSServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get DNS server params
func (o *GetDNSServerParams) WithContext(ctx context.Context) *GetDNSServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get DNS server params
func (o *GetDNSServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get DNS server params
func (o *GetDNSServerParams) WithHTTPClient(client *http.Client) *GetDNSServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get DNS server params
func (o *GetDNSServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the get DNS server params
func (o *GetDNSServerParams) WithServerID(serverID string) *GetDNSServerParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the get DNS server params
func (o *GetDNSServerParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDNSServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serverId
	if err := r.SetPathParam("serverId", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
