// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAllDNSZoneRecordsReader is a Reader for the GetAllDNSZoneRecords structure.
type GetAllDNSZoneRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllDNSZoneRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllDNSZoneRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAllDNSZoneRecordsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllDNSZoneRecordsOK creates a GetAllDNSZoneRecordsOK with default headers values
func NewGetAllDNSZoneRecordsOK() *GetAllDNSZoneRecordsOK {
	return &GetAllDNSZoneRecordsOK{}
}

/*
GetAllDNSZoneRecordsOK describes a response with status code 200, with default header values.

Returns the an array of zone's record IDs.
*/
type GetAllDNSZoneRecordsOK struct {
	Payload []string
}

// IsSuccess returns true when this get all Dns zone records o k response has a 2xx status code
func (o *GetAllDNSZoneRecordsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all Dns zone records o k response has a 3xx status code
func (o *GetAllDNSZoneRecordsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all Dns zone records o k response has a 4xx status code
func (o *GetAllDNSZoneRecordsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all Dns zone records o k response has a 5xx status code
func (o *GetAllDNSZoneRecordsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all Dns zone records o k response a status code equal to that given
func (o *GetAllDNSZoneRecordsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all Dns zone records o k response
func (o *GetAllDNSZoneRecordsOK) Code() int {
	return 200
}

func (o *GetAllDNSZoneRecordsOK) Error() string {
	return fmt.Sprintf("[GET /dns/zone/{zoneId}/record][%d] getAllDnsZoneRecordsOK  %+v", 200, o.Payload)
}

func (o *GetAllDNSZoneRecordsOK) String() string {
	return fmt.Sprintf("[GET /dns/zone/{zoneId}/record][%d] getAllDnsZoneRecordsOK  %+v", 200, o.Payload)
}

func (o *GetAllDNSZoneRecordsOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAllDNSZoneRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllDNSZoneRecordsNotFound creates a GetAllDNSZoneRecordsNotFound with default headers values
func NewGetAllDNSZoneRecordsNotFound() *GetAllDNSZoneRecordsNotFound {
	return &GetAllDNSZoneRecordsNotFound{}
}

/*
GetAllDNSZoneRecordsNotFound describes a response with status code 404, with default header values.

Invalid zone ID was provided.
*/
type GetAllDNSZoneRecordsNotFound struct {
}

// IsSuccess returns true when this get all Dns zone records not found response has a 2xx status code
func (o *GetAllDNSZoneRecordsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all Dns zone records not found response has a 3xx status code
func (o *GetAllDNSZoneRecordsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all Dns zone records not found response has a 4xx status code
func (o *GetAllDNSZoneRecordsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all Dns zone records not found response has a 5xx status code
func (o *GetAllDNSZoneRecordsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get all Dns zone records not found response a status code equal to that given
func (o *GetAllDNSZoneRecordsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get all Dns zone records not found response
func (o *GetAllDNSZoneRecordsNotFound) Code() int {
	return 404
}

func (o *GetAllDNSZoneRecordsNotFound) Error() string {
	return fmt.Sprintf("[GET /dns/zone/{zoneId}/record][%d] getAllDnsZoneRecordsNotFound ", 404)
}

func (o *GetAllDNSZoneRecordsNotFound) String() string {
	return fmt.Sprintf("[GET /dns/zone/{zoneId}/record][%d] getAllDnsZoneRecordsNotFound ", 404)
}

func (o *GetAllDNSZoneRecordsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
