// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/iris-api/models"
)

// GetDNSServerReader is a Reader for the GetDNSServer structure.
type GetDNSServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDNSServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDNSServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDNSServerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDNSServerOK creates a GetDNSServerOK with default headers values
func NewGetDNSServerOK() *GetDNSServerOK {
	return &GetDNSServerOK{}
}

/*
GetDNSServerOK describes a response with status code 200, with default header values.

Returns the DNSServer object.
*/
type GetDNSServerOK struct {
	Payload *models.DNSServer
}

// IsSuccess returns true when this get Dns server o k response has a 2xx status code
func (o *GetDNSServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Dns server o k response has a 3xx status code
func (o *GetDNSServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server o k response has a 4xx status code
func (o *GetDNSServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Dns server o k response has a 5xx status code
func (o *GetDNSServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server o k response a status code equal to that given
func (o *GetDNSServerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Dns server o k response
func (o *GetDNSServerOK) Code() int {
	return 200
}

func (o *GetDNSServerOK) Error() string {
	return fmt.Sprintf("[GET /dns/server/{serverId}][%d] getDnsServerOK  %+v", 200, o.Payload)
}

func (o *GetDNSServerOK) String() string {
	return fmt.Sprintf("[GET /dns/server/{serverId}][%d] getDnsServerOK  %+v", 200, o.Payload)
}

func (o *GetDNSServerOK) GetPayload() *models.DNSServer {
	return o.Payload
}

func (o *GetDNSServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DNSServer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSServerNotFound creates a GetDNSServerNotFound with default headers values
func NewGetDNSServerNotFound() *GetDNSServerNotFound {
	return &GetDNSServerNotFound{}
}

/*
GetDNSServerNotFound describes a response with status code 404, with default header values.

Invalid server ID was provided.
*/
type GetDNSServerNotFound struct {
}

// IsSuccess returns true when this get Dns server not found response has a 2xx status code
func (o *GetDNSServerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Dns server not found response has a 3xx status code
func (o *GetDNSServerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns server not found response has a 4xx status code
func (o *GetDNSServerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Dns server not found response has a 5xx status code
func (o *GetDNSServerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns server not found response a status code equal to that given
func (o *GetDNSServerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Dns server not found response
func (o *GetDNSServerNotFound) Code() int {
	return 404
}

func (o *GetDNSServerNotFound) Error() string {
	return fmt.Sprintf("[GET /dns/server/{serverId}][%d] getDnsServerNotFound ", 404)
}

func (o *GetDNSServerNotFound) String() string {
	return fmt.Sprintf("[GET /dns/server/{serverId}][%d] getDnsServerNotFound ", 404)
}

func (o *GetDNSServerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
