// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/iris-api/models"
)

// NewUpdateDNSZoneParams creates a new UpdateDNSZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDNSZoneParams() *UpdateDNSZoneParams {
	return &UpdateDNSZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDNSZoneParamsWithTimeout creates a new UpdateDNSZoneParams object
// with the ability to set a timeout on a request.
func NewUpdateDNSZoneParamsWithTimeout(timeout time.Duration) *UpdateDNSZoneParams {
	return &UpdateDNSZoneParams{
		timeout: timeout,
	}
}

// NewUpdateDNSZoneParamsWithContext creates a new UpdateDNSZoneParams object
// with the ability to set a context for a request.
func NewUpdateDNSZoneParamsWithContext(ctx context.Context) *UpdateDNSZoneParams {
	return &UpdateDNSZoneParams{
		Context: ctx,
	}
}

// NewUpdateDNSZoneParamsWithHTTPClient creates a new UpdateDNSZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDNSZoneParamsWithHTTPClient(client *http.Client) *UpdateDNSZoneParams {
	return &UpdateDNSZoneParams{
		HTTPClient: client,
	}
}

/*
UpdateDNSZoneParams contains all the parameters to send to the API endpoint

	for the update DNS zone operation.

	Typically these are written to a http.Request.
*/
type UpdateDNSZoneParams struct {

	// Body.
	Body *models.Zone

	/* ZoneID.

	   The ID of the zone to update.
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update DNS zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDNSZoneParams) WithDefaults() *UpdateDNSZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update DNS zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDNSZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update DNS zone params
func (o *UpdateDNSZoneParams) WithTimeout(timeout time.Duration) *UpdateDNSZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update DNS zone params
func (o *UpdateDNSZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update DNS zone params
func (o *UpdateDNSZoneParams) WithContext(ctx context.Context) *UpdateDNSZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update DNS zone params
func (o *UpdateDNSZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update DNS zone params
func (o *UpdateDNSZoneParams) WithHTTPClient(client *http.Client) *UpdateDNSZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update DNS zone params
func (o *UpdateDNSZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update DNS zone params
func (o *UpdateDNSZoneParams) WithBody(body *models.Zone) *UpdateDNSZoneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update DNS zone params
func (o *UpdateDNSZoneParams) SetBody(body *models.Zone) {
	o.Body = body
}

// WithZoneID adds the zoneID to the update DNS zone params
func (o *UpdateDNSZoneParams) WithZoneID(zoneID string) *UpdateDNSZoneParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the update DNS zone params
func (o *UpdateDNSZoneParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDNSZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param zoneId
	if err := r.SetPathParam("zoneId", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
