// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EnableDNSZoneRecordCreatedCode is the HTTP code returned for type EnableDNSZoneRecordCreated
const EnableDNSZoneRecordCreatedCode int = 201

/*
EnableDNSZoneRecordCreated The DNS zone's record has been enabled.

swagger:response enableDnsZoneRecordCreated
*/
type EnableDNSZoneRecordCreated struct {
}

// NewEnableDNSZoneRecordCreated creates EnableDNSZoneRecordCreated with default headers values
func NewEnableDNSZoneRecordCreated() *EnableDNSZoneRecordCreated {

	return &EnableDNSZoneRecordCreated{}
}

// WriteResponse to the client
func (o *EnableDNSZoneRecordCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EnableDNSZoneRecordConflictCode is the HTTP code returned for type EnableDNSZoneRecordConflict
const EnableDNSZoneRecordConflictCode int = 409

/*
EnableDNSZoneRecordConflict The DNS zone's record was already enable.

swagger:response enableDnsZoneRecordConflict
*/
type EnableDNSZoneRecordConflict struct {
}

// NewEnableDNSZoneRecordConflict creates EnableDNSZoneRecordConflict with default headers values
func NewEnableDNSZoneRecordConflict() *EnableDNSZoneRecordConflict {

	return &EnableDNSZoneRecordConflict{}
}

// WriteResponse to the client
func (o *EnableDNSZoneRecordConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// EnableDNSZoneRecordInternalServerErrorCode is the HTTP code returned for type EnableDNSZoneRecordInternalServerError
const EnableDNSZoneRecordInternalServerErrorCode int = 500

/*
EnableDNSZoneRecordInternalServerError Unable to enable the DNS zone's record.

swagger:response enableDnsZoneRecordInternalServerError
*/
type EnableDNSZoneRecordInternalServerError struct {
}

// NewEnableDNSZoneRecordInternalServerError creates EnableDNSZoneRecordInternalServerError with default headers values
func NewEnableDNSZoneRecordInternalServerError() *EnableDNSZoneRecordInternalServerError {

	return &EnableDNSZoneRecordInternalServerError{}
}

// WriteResponse to the client
func (o *EnableDNSZoneRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
