// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetDNSServerParams creates a new GetDNSServerParams object
//
// There are no default values defined in the spec.
func NewGetDNSServerParams() GetDNSServerParams {

	return GetDNSServerParams{}
}

// GetDNSServerParams contains all the bound params for the get DNS server operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetDNSServer
type GetDNSServerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the DNS server to query.
	  Required: true
	  In: path
	*/
	ServerID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDNSServerParams() beforehand.
func (o *GetDNSServerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rServerID, rhkServerID, _ := route.Params.GetOK("serverId")
	if err := o.bindServerID(rServerID, rhkServerID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindServerID binds and validates parameter ServerID from path.
func (o *GetDNSServerParams) bindServerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ServerID = raw

	return nil
}
