// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAllDNSServersHandlerFunc turns a function with the right signature into a get all DNS servers handler
type GetAllDNSServersHandlerFunc func(GetAllDNSServersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllDNSServersHandlerFunc) Handle(params GetAllDNSServersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllDNSServersHandler interface for that can handle valid get all DNS servers params
type GetAllDNSServersHandler interface {
	Handle(GetAllDNSServersParams, interface{}) middleware.Responder
}

// NewGetAllDNSServers creates a new http.Handler for the get all DNS servers operation
func NewGetAllDNSServers(ctx *middleware.Context, handler GetAllDNSServersHandler) *GetAllDNSServers {
	return &GetAllDNSServers{Context: ctx, Handler: handler}
}

/*
	GetAllDNSServers swagger:route GET /dns/server dns getAllDnsServers

Returns the IDs of DNS servers.
*/
type GetAllDNSServers struct {
	Context *middleware.Context
	Handler GetAllDNSServersHandler
}

func (o *GetAllDNSServers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAllDNSServersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
