// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// GetDNSServerOKCode is the HTTP code returned for type GetDNSServerOK
const GetDNSServerOKCode int = 200

/*
GetDNSServerOK Returns the DNSServer object.

swagger:response getDnsServerOK
*/
type GetDNSServerOK struct {

	/*
	  In: Body
	*/
	Payload *models.DNSServer `json:"body,omitempty"`
}

// NewGetDNSServerOK creates GetDNSServerOK with default headers values
func NewGetDNSServerOK() *GetDNSServerOK {

	return &GetDNSServerOK{}
}

// WithPayload adds the payload to the get Dns server o k response
func (o *GetDNSServerOK) WithPayload(payload *models.DNSServer) *GetDNSServerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Dns server o k response
func (o *GetDNSServerOK) SetPayload(payload *models.DNSServer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDNSServerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDNSServerNotFoundCode is the HTTP code returned for type GetDNSServerNotFound
const GetDNSServerNotFoundCode int = 404

/*
GetDNSServerNotFound Invalid server ID was provided.

swagger:response getDnsServerNotFound
*/
type GetDNSServerNotFound struct {
}

// NewGetDNSServerNotFound creates GetDNSServerNotFound with default headers values
func NewGetDNSServerNotFound() *GetDNSServerNotFound {

	return &GetDNSServerNotFound{}
}

// WriteResponse to the client
func (o *GetDNSServerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
