// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// GetDNSZoneOKCode is the HTTP code returned for type GetDNSZoneOK
const GetDNSZoneOKCode int = 200

/*
GetDNSZoneOK Returns the DNS Zone object.

swagger:response getDnsZoneOK
*/
type GetDNSZoneOK struct {

	/*
	  In: Body
	*/
	Payload *models.Zone `json:"body,omitempty"`
}

// NewGetDNSZoneOK creates GetDNSZoneOK with default headers values
func NewGetDNSZoneOK() *GetDNSZoneOK {

	return &GetDNSZoneOK{}
}

// WithPayload adds the payload to the get Dns zone o k response
func (o *GetDNSZoneOK) WithPayload(payload *models.Zone) *GetDNSZoneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Dns zone o k response
func (o *GetDNSZoneOK) SetPayload(payload *models.Zone) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDNSZoneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDNSZoneNotFoundCode is the HTTP code returned for type GetDNSZoneNotFound
const GetDNSZoneNotFoundCode int = 404

/*
GetDNSZoneNotFound Invalid zone ID was provided.

swagger:response getDnsZoneNotFound
*/
type GetDNSZoneNotFound struct {
}

// NewGetDNSZoneNotFound creates GetDNSZoneNotFound with default headers values
func NewGetDNSZoneNotFound() *GetDNSZoneNotFound {

	return &GetDNSZoneNotFound{}
}

// WriteResponse to the client
func (o *GetDNSZoneNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
