// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAllDNSZoneRecordsOKCode is the HTTP code returned for type GetAllDNSZoneRecordsOK
const GetAllDNSZoneRecordsOKCode int = 200

/*
GetAllDNSZoneRecordsOK Returns the an array of zone's record IDs.

swagger:response getAllDnsZoneRecordsOK
*/
type GetAllDNSZoneRecordsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetAllDNSZoneRecordsOK creates GetAllDNSZoneRecordsOK with default headers values
func NewGetAllDNSZoneRecordsOK() *GetAllDNSZoneRecordsOK {

	return &GetAllDNSZoneRecordsOK{}
}

// WithPayload adds the payload to the get all Dns zone records o k response
func (o *GetAllDNSZoneRecordsOK) WithPayload(payload []string) *GetAllDNSZoneRecordsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all Dns zone records o k response
func (o *GetAllDNSZoneRecordsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllDNSZoneRecordsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllDNSZoneRecordsNotFoundCode is the HTTP code returned for type GetAllDNSZoneRecordsNotFound
const GetAllDNSZoneRecordsNotFoundCode int = 404

/*
GetAllDNSZoneRecordsNotFound Invalid zone ID was provided.

swagger:response getAllDnsZoneRecordsNotFound
*/
type GetAllDNSZoneRecordsNotFound struct {
}

// NewGetAllDNSZoneRecordsNotFound creates GetAllDNSZoneRecordsNotFound with default headers values
func NewGetAllDNSZoneRecordsNotFound() *GetAllDNSZoneRecordsNotFound {

	return &GetAllDNSZoneRecordsNotFound{}
}

// WriteResponse to the client
func (o *GetAllDNSZoneRecordsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
