// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// UpdateDNSZoneRecordOKCode is the HTTP code returned for type UpdateDNSZoneRecordOK
const UpdateDNSZoneRecordOKCode int = 200

/*
UpdateDNSZoneRecordOK Returns the updated Record object.

swagger:response updateDnsZoneRecordOK
*/
type UpdateDNSZoneRecordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Record `json:"body,omitempty"`
}

// NewUpdateDNSZoneRecordOK creates UpdateDNSZoneRecordOK with default headers values
func NewUpdateDNSZoneRecordOK() *UpdateDNSZoneRecordOK {

	return &UpdateDNSZoneRecordOK{}
}

// WithPayload adds the payload to the update Dns zone record o k response
func (o *UpdateDNSZoneRecordOK) WithPayload(payload *models.Record) *UpdateDNSZoneRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Dns zone record o k response
func (o *UpdateDNSZoneRecordOK) SetPayload(payload *models.Record) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDNSZoneRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDNSZoneRecordBadRequestCode is the HTTP code returned for type UpdateDNSZoneRecordBadRequest
const UpdateDNSZoneRecordBadRequestCode int = 400

/*
UpdateDNSZoneRecordBadRequest Bad parameters were provided.

swagger:response updateDnsZoneRecordBadRequest
*/
type UpdateDNSZoneRecordBadRequest struct {
}

// NewUpdateDNSZoneRecordBadRequest creates UpdateDNSZoneRecordBadRequest with default headers values
func NewUpdateDNSZoneRecordBadRequest() *UpdateDNSZoneRecordBadRequest {

	return &UpdateDNSZoneRecordBadRequest{}
}

// WriteResponse to the client
func (o *UpdateDNSZoneRecordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateDNSZoneRecordNotFoundCode is the HTTP code returned for type UpdateDNSZoneRecordNotFound
const UpdateDNSZoneRecordNotFoundCode int = 404

/*
UpdateDNSZoneRecordNotFound Invalid zone ID or record ID was provided.

swagger:response updateDnsZoneRecordNotFound
*/
type UpdateDNSZoneRecordNotFound struct {
}

// NewUpdateDNSZoneRecordNotFound creates UpdateDNSZoneRecordNotFound with default headers values
func NewUpdateDNSZoneRecordNotFound() *UpdateDNSZoneRecordNotFound {

	return &UpdateDNSZoneRecordNotFound{}
}

// WriteResponse to the client
func (o *UpdateDNSZoneRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateDNSZoneRecordInternalServerErrorCode is the HTTP code returned for type UpdateDNSZoneRecordInternalServerError
const UpdateDNSZoneRecordInternalServerErrorCode int = 500

/*
UpdateDNSZoneRecordInternalServerError Unable to update zone's record.

swagger:response updateDnsZoneRecordInternalServerError
*/
type UpdateDNSZoneRecordInternalServerError struct {
}

// NewUpdateDNSZoneRecordInternalServerError creates UpdateDNSZoneRecordInternalServerError with default headers values
func NewUpdateDNSZoneRecordInternalServerError() *UpdateDNSZoneRecordInternalServerError {

	return &UpdateDNSZoneRecordInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateDNSZoneRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
