// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateDHCPSubnetHandlerFunc turns a function with the right signature into a create d h c p subnet handler
type CreateDHCPSubnetHandlerFunc func(CreateDHCPSubnetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDHCPSubnetHandlerFunc) Handle(params CreateDHCPSubnetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateDHCPSubnetHandler interface for that can handle valid create d h c p subnet params
type CreateDHCPSubnetHandler interface {
	Handle(CreateDHCPSubnetParams, interface{}) middleware.Responder
}

// NewCreateDHCPSubnet creates a new http.Handler for the create d h c p subnet operation
func NewCreateDHCPSubnet(ctx *middleware.Context, handler CreateDHCPSubnetHandler) *CreateDHCPSubnet {
	return &CreateDHCPSubnet{Context: ctx, Handler: handler}
}

/*
	CreateDHCPSubnet swagger:route POST /dhcp/subnet dhcp createDHCPSubnet

Creates a new DHCPv4 subnet.
*/
type CreateDHCPSubnet struct {
	Context *middleware.Context
	Handler CreateDHCPSubnetHandler
}

func (o *CreateDHCPSubnet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateDHCPSubnetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
