// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// CreateDHCPSubnetCreatedCode is the HTTP code returned for type CreateDHCPSubnetCreated
const CreateDHCPSubnetCreatedCode int = 201

/*
CreateDHCPSubnetCreated Returns the newly created subnet object.

swagger:response createDHCPSubnetCreated
*/
type CreateDHCPSubnetCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Subnet `json:"body,omitempty"`
}

// NewCreateDHCPSubnetCreated creates CreateDHCPSubnetCreated with default headers values
func NewCreateDHCPSubnetCreated() *CreateDHCPSubnetCreated {

	return &CreateDHCPSubnetCreated{}
}

// WithPayload adds the payload to the create d h c p subnet created response
func (o *CreateDHCPSubnetCreated) WithPayload(payload *models.Subnet) *CreateDHCPSubnetCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create d h c p subnet created response
func (o *CreateDHCPSubnetCreated) SetPayload(payload *models.Subnet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDHCPSubnetCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateDHCPSubnetBadRequestCode is the HTTP code returned for type CreateDHCPSubnetBadRequest
const CreateDHCPSubnetBadRequestCode int = 400

/*
CreateDHCPSubnetBadRequest Bad parameters were provided.

swagger:response createDHCPSubnetBadRequest
*/
type CreateDHCPSubnetBadRequest struct {
}

// NewCreateDHCPSubnetBadRequest creates CreateDHCPSubnetBadRequest with default headers values
func NewCreateDHCPSubnetBadRequest() *CreateDHCPSubnetBadRequest {

	return &CreateDHCPSubnetBadRequest{}
}

// WriteResponse to the client
func (o *CreateDHCPSubnetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateDHCPSubnetConflictCode is the HTTP code returned for type CreateDHCPSubnetConflict
const CreateDHCPSubnetConflictCode int = 409

/*
CreateDHCPSubnetConflict Subnet already exists.

swagger:response createDHCPSubnetConflict
*/
type CreateDHCPSubnetConflict struct {
}

// NewCreateDHCPSubnetConflict creates CreateDHCPSubnetConflict with default headers values
func NewCreateDHCPSubnetConflict() *CreateDHCPSubnetConflict {

	return &CreateDHCPSubnetConflict{}
}

// WriteResponse to the client
func (o *CreateDHCPSubnetConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateDHCPSubnetInternalServerErrorCode is the HTTP code returned for type CreateDHCPSubnetInternalServerError
const CreateDHCPSubnetInternalServerErrorCode int = 500

/*
CreateDHCPSubnetInternalServerError Unable to create Subnet's resevration.

swagger:response createDHCPSubnetInternalServerError
*/
type CreateDHCPSubnetInternalServerError struct {
}

// NewCreateDHCPSubnetInternalServerError creates CreateDHCPSubnetInternalServerError with default headers values
func NewCreateDHCPSubnetInternalServerError() *CreateDHCPSubnetInternalServerError {

	return &CreateDHCPSubnetInternalServerError{}
}

// WriteResponse to the client
func (o *CreateDHCPSubnetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
