// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateDHCPSubnetReservationHandlerFunc turns a function with the right signature into a create d h c p subnet reservation handler
type CreateDHCPSubnetReservationHandlerFunc func(CreateDHCPSubnetReservationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDHCPSubnetReservationHandlerFunc) Handle(params CreateDHCPSubnetReservationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateDHCPSubnetReservationHandler interface for that can handle valid create d h c p subnet reservation params
type CreateDHCPSubnetReservationHandler interface {
	Handle(CreateDHCPSubnetReservationParams, interface{}) middleware.Responder
}

// NewCreateDHCPSubnetReservation creates a new http.Handler for the create d h c p subnet reservation operation
func NewCreateDHCPSubnetReservation(ctx *middleware.Context, handler CreateDHCPSubnetReservationHandler) *CreateDHCPSubnetReservation {
	return &CreateDHCPSubnetReservation{Context: ctx, Handler: handler}
}

/*
	CreateDHCPSubnetReservation swagger:route POST /dhcp/subnet/{subnetId}/reservation dhcp createDHCPSubnetReservation

Creates a new DHCPv4 subnet's reservation.
*/
type CreateDHCPSubnetReservation struct {
	Context *middleware.Context
	Handler CreateDHCPSubnetReservationHandler
}

func (o *CreateDHCPSubnetReservation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateDHCPSubnetReservationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
