// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDHCPSubnetReservationParams creates a new DeleteDHCPSubnetReservationParams object
//
// There are no default values defined in the spec.
func NewDeleteDHCPSubnetReservationParams() DeleteDHCPSubnetReservationParams {

	return DeleteDHCPSubnetReservationParams{}
}

// DeleteDHCPSubnetReservationParams contains all the bound params for the delete d h c p subnet reservation operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteDHCPSubnetReservation
type DeleteDHCPSubnetReservationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The hardware MAC address of the reservation to delete.
	  Required: true
	  In: path
	*/
	MacID string
	/*The ID of the subnet's reservation to delete.
	  Required: true
	  In: path
	*/
	SubnetID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteDHCPSubnetReservationParams() beforehand.
func (o *DeleteDHCPSubnetReservationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rMacID, rhkMacID, _ := route.Params.GetOK("macID")
	if err := o.bindMacID(rMacID, rhkMacID, route.Formats); err != nil {
		res = append(res, err)
	}

	rSubnetID, rhkSubnetID, _ := route.Params.GetOK("subnetId")
	if err := o.bindSubnetID(rSubnetID, rhkSubnetID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMacID binds and validates parameter MacID from path.
func (o *DeleteDHCPSubnetReservationParams) bindMacID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.MacID = raw

	return nil
}

// bindSubnetID binds and validates parameter SubnetID from path.
func (o *DeleteDHCPSubnetReservationParams) bindSubnetID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SubnetID = raw

	return nil
}
