// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDHCPSubnetOKCode is the HTTP code returned for type DeleteDHCPSubnetOK
const DeleteDHCPSubnetOKCode int = 200

/*
DeleteDHCPSubnetOK The subnet has been successfully removed.

swagger:response deleteDHCPSubnetOK
*/
type DeleteDHCPSubnetOK struct {
}

// NewDeleteDHCPSubnetOK creates DeleteDHCPSubnetOK with default headers values
func NewDeleteDHCPSubnetOK() *DeleteDHCPSubnetOK {

	return &DeleteDHCPSubnetOK{}
}

// WriteResponse to the client
func (o *DeleteDHCPSubnetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteDHCPSubnetNotFoundCode is the HTTP code returned for type DeleteDHCPSubnetNotFound
const DeleteDHCPSubnetNotFoundCode int = 404

/*
DeleteDHCPSubnetNotFound Invalid subnet ID was provided.

swagger:response deleteDHCPSubnetNotFound
*/
type DeleteDHCPSubnetNotFound struct {
}

// NewDeleteDHCPSubnetNotFound creates DeleteDHCPSubnetNotFound with default headers values
func NewDeleteDHCPSubnetNotFound() *DeleteDHCPSubnetNotFound {

	return &DeleteDHCPSubnetNotFound{}
}

// WriteResponse to the client
func (o *DeleteDHCPSubnetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteDHCPSubnetConflictCode is the HTTP code returned for type DeleteDHCPSubnetConflict
const DeleteDHCPSubnetConflictCode int = 409

/*
DeleteDHCPSubnetConflict The subnet is not empty or still has reservations.

swagger:response deleteDHCPSubnetConflict
*/
type DeleteDHCPSubnetConflict struct {
}

// NewDeleteDHCPSubnetConflict creates DeleteDHCPSubnetConflict with default headers values
func NewDeleteDHCPSubnetConflict() *DeleteDHCPSubnetConflict {

	return &DeleteDHCPSubnetConflict{}
}

// WriteResponse to the client
func (o *DeleteDHCPSubnetConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// DeleteDHCPSubnetInternalServerErrorCode is the HTTP code returned for type DeleteDHCPSubnetInternalServerError
const DeleteDHCPSubnetInternalServerErrorCode int = 500

/*
DeleteDHCPSubnetInternalServerError Unable to remove the requested subnet.

swagger:response deleteDHCPSubnetInternalServerError
*/
type DeleteDHCPSubnetInternalServerError struct {
}

// NewDeleteDHCPSubnetInternalServerError creates DeleteDHCPSubnetInternalServerError with default headers values
func NewDeleteDHCPSubnetInternalServerError() *DeleteDHCPSubnetInternalServerError {

	return &DeleteDHCPSubnetInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteDHCPSubnetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
