// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DisableDHCPHandlerFunc turns a function with the right signature into a disable d h c p handler
type DisableDHCPHandlerFunc func(DisableDHCPParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DisableDHCPHandlerFunc) Handle(params DisableDHCPParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DisableDHCPHandler interface for that can handle valid disable d h c p params
type DisableDHCPHandler interface {
	Handle(DisableDHCPParams, interface{}) middleware.Responder
}

// NewDisableDHCP creates a new http.Handler for the disable d h c p operation
func NewDisableDHCP(ctx *middleware.Context, handler DisableDHCPHandler) *DisableDHCP {
	return &DisableDHCP{Context: ctx, Handler: handler}
}

/*
	DisableDHCP swagger:route POST /dhcp/disable dhcp disableDHCP

Disable the DHCPv4 service.
*/
type DisableDHCP struct {
	Context *middleware.Context
	Handler DisableDHCPHandler
}

func (o *DisableDHCP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDisableDHCPParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
