// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EnableDHCPCreatedCode is the HTTP code returned for type EnableDHCPCreated
const EnableDHCPCreatedCode int = 201

/*
EnableDHCPCreated The DHCPv4 service has been enabled.

swagger:response enableDHCPCreated
*/
type EnableDHCPCreated struct {
}

// NewEnableDHCPCreated creates EnableDHCPCreated with default headers values
func NewEnableDHCPCreated() *EnableDHCPCreated {

	return &EnableDHCPCreated{}
}

// WriteResponse to the client
func (o *EnableDHCPCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EnableDHCPConflictCode is the HTTP code returned for type EnableDHCPConflict
const EnableDHCPConflictCode int = 409

/*
EnableDHCPConflict The DHCPv4 service was already enable.

swagger:response enableDHCPConflict
*/
type EnableDHCPConflict struct {
}

// NewEnableDHCPConflict creates EnableDHCPConflict with default headers values
func NewEnableDHCPConflict() *EnableDHCPConflict {

	return &EnableDHCPConflict{}
}

// WriteResponse to the client
func (o *EnableDHCPConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// EnableDHCPInternalServerErrorCode is the HTTP code returned for type EnableDHCPInternalServerError
const EnableDHCPInternalServerErrorCode int = 500

/*
EnableDHCPInternalServerError Unable to enable the DHCPv4 service.

swagger:response enableDHCPInternalServerError
*/
type EnableDHCPInternalServerError struct {
}

// NewEnableDHCPInternalServerError creates EnableDHCPInternalServerError with default headers values
func NewEnableDHCPInternalServerError() *EnableDHCPInternalServerError {

	return &EnableDHCPInternalServerError{}
}

// WriteResponse to the client
func (o *EnableDHCPInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
