// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDHCPSubnetReservationHandlerFunc turns a function with the right signature into a get d h c p subnet reservation handler
type GetDHCPSubnetReservationHandlerFunc func(GetDHCPSubnetReservationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDHCPSubnetReservationHandlerFunc) Handle(params GetDHCPSubnetReservationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDHCPSubnetReservationHandler interface for that can handle valid get d h c p subnet reservation params
type GetDHCPSubnetReservationHandler interface {
	Handle(GetDHCPSubnetReservationParams, interface{}) middleware.Responder
}

// NewGetDHCPSubnetReservation creates a new http.Handler for the get d h c p subnet reservation operation
func NewGetDHCPSubnetReservation(ctx *middleware.Context, handler GetDHCPSubnetReservationHandler) *GetDHCPSubnetReservation {
	return &GetDHCPSubnetReservation{Context: ctx, Handler: handler}
}

/*
	GetDHCPSubnetReservation swagger:route GET /dhcp/subnet/{subnetId}/reservation/{macID} dhcp getDHCPSubnetReservation

Returns the subnet reservation object.
*/
type GetDHCPSubnetReservation struct {
	Context *middleware.Context
	Handler GetDHCPSubnetReservationHandler
}

func (o *GetDHCPSubnetReservation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDHCPSubnetReservationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
