// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// GetDHCPStatusOKCode is the HTTP code returned for type GetDHCPStatusOK
const GetDHCPStatusOKCode int = 200

/*
GetDHCPStatusOK Return the status and version of the DHCPv4 service.

swagger:response getDHCPStatusOK
*/
type GetDHCPStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.DHCP `json:"body,omitempty"`
}

// NewGetDHCPStatusOK creates GetDHCPStatusOK with default headers values
func NewGetDHCPStatusOK() *GetDHCPStatusOK {

	return &GetDHCPStatusOK{}
}

// WithPayload adds the payload to the get d h c p status o k response
func (o *GetDHCPStatusOK) WithPayload(payload *models.DHCP) *GetDHCPStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get d h c p status o k response
func (o *GetDHCPStatusOK) SetPayload(payload *models.DHCP) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDHCPStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
