// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDHCPStatusHandlerFunc turns a function with the right signature into a get d h c p status handler
type GetDHCPStatusHandlerFunc func(GetDHCPStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDHCPStatusHandlerFunc) Handle(params GetDHCPStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDHCPStatusHandler interface for that can handle valid get d h c p status params
type GetDHCPStatusHandler interface {
	Handle(GetDHCPStatusParams, interface{}) middleware.Responder
}

// NewGetDHCPStatus creates a new http.Handler for the get d h c p status operation
func NewGetDHCPStatus(ctx *middleware.Context, handler GetDHCPStatusHandler) *GetDHCPStatus {
	return &GetDHCPStatus{Context: ctx, Handler: handler}
}

/*
	GetDHCPStatus swagger:route GET /dhcp dhcp getDHCPStatus

Return the status of the DHCPv4 service.
*/
type GetDHCPStatus struct {
	Context *middleware.Context
	Handler GetDHCPStatusHandler
}

func (o *GetDHCPStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDHCPStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
