// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateDHCPSubnetReservationHandlerFunc turns a function with the right signature into a update d h c p subnet reservation handler
type UpdateDHCPSubnetReservationHandlerFunc func(UpdateDHCPSubnetReservationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDHCPSubnetReservationHandlerFunc) Handle(params UpdateDHCPSubnetReservationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateDHCPSubnetReservationHandler interface for that can handle valid update d h c p subnet reservation params
type UpdateDHCPSubnetReservationHandler interface {
	Handle(UpdateDHCPSubnetReservationParams, interface{}) middleware.Responder
}

// NewUpdateDHCPSubnetReservation creates a new http.Handler for the update d h c p subnet reservation operation
func NewUpdateDHCPSubnetReservation(ctx *middleware.Context, handler UpdateDHCPSubnetReservationHandler) *UpdateDHCPSubnetReservation {
	return &UpdateDHCPSubnetReservation{Context: ctx, Handler: handler}
}

/*
	UpdateDHCPSubnetReservation swagger:route PUT /dhcp/subnet/{subnetId}/reservation/{macID} dhcp updateDHCPSubnetReservation

Updates a DHCPv4 subnet reservation.
*/
type UpdateDHCPSubnetReservation struct {
	Context *middleware.Context
	Handler UpdateDHCPSubnetReservationHandler
}

func (o *UpdateDHCPSubnetReservation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateDHCPSubnetReservationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
