// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/iris-api/models"
)

// UpdateDHCPSubnetOKCode is the HTTP code returned for type UpdateDHCPSubnetOK
const UpdateDHCPSubnetOKCode int = 200

/*
UpdateDHCPSubnetOK Returns the updated subnet object.

swagger:response updateDHCPSubnetOK
*/
type UpdateDHCPSubnetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Subnet `json:"body,omitempty"`
}

// NewUpdateDHCPSubnetOK creates UpdateDHCPSubnetOK with default headers values
func NewUpdateDHCPSubnetOK() *UpdateDHCPSubnetOK {

	return &UpdateDHCPSubnetOK{}
}

// WithPayload adds the payload to the update d h c p subnet o k response
func (o *UpdateDHCPSubnetOK) WithPayload(payload *models.Subnet) *UpdateDHCPSubnetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update d h c p subnet o k response
func (o *UpdateDHCPSubnetOK) SetPayload(payload *models.Subnet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDHCPSubnetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDHCPSubnetBadRequestCode is the HTTP code returned for type UpdateDHCPSubnetBadRequest
const UpdateDHCPSubnetBadRequestCode int = 400

/*
UpdateDHCPSubnetBadRequest Bad parameters were provided.

swagger:response updateDHCPSubnetBadRequest
*/
type UpdateDHCPSubnetBadRequest struct {
}

// NewUpdateDHCPSubnetBadRequest creates UpdateDHCPSubnetBadRequest with default headers values
func NewUpdateDHCPSubnetBadRequest() *UpdateDHCPSubnetBadRequest {

	return &UpdateDHCPSubnetBadRequest{}
}

// WriteResponse to the client
func (o *UpdateDHCPSubnetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateDHCPSubnetNotFoundCode is the HTTP code returned for type UpdateDHCPSubnetNotFound
const UpdateDHCPSubnetNotFoundCode int = 404

/*
UpdateDHCPSubnetNotFound Invalid subnet ID was provided.

swagger:response updateDHCPSubnetNotFound
*/
type UpdateDHCPSubnetNotFound struct {
}

// NewUpdateDHCPSubnetNotFound creates UpdateDHCPSubnetNotFound with default headers values
func NewUpdateDHCPSubnetNotFound() *UpdateDHCPSubnetNotFound {

	return &UpdateDHCPSubnetNotFound{}
}

// WriteResponse to the client
func (o *UpdateDHCPSubnetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateDHCPSubnetInternalServerErrorCode is the HTTP code returned for type UpdateDHCPSubnetInternalServerError
const UpdateDHCPSubnetInternalServerErrorCode int = 500

/*
UpdateDHCPSubnetInternalServerError Unable to update subnet.

swagger:response updateDHCPSubnetInternalServerError
*/
type UpdateDHCPSubnetInternalServerError struct {
}

// NewUpdateDHCPSubnetInternalServerError creates UpdateDHCPSubnetInternalServerError with default headers values
func NewUpdateDHCPSubnetInternalServerError() *UpdateDHCPSubnetInternalServerError {

	return &UpdateDHCPSubnetInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateDHCPSubnetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
