// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateDHCPSubnetHandlerFunc turns a function with the right signature into a update d h c p subnet handler
type UpdateDHCPSubnetHandlerFunc func(UpdateDHCPSubnetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDHCPSubnetHandlerFunc) Handle(params UpdateDHCPSubnetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateDHCPSubnetHandler interface for that can handle valid update d h c p subnet params
type UpdateDHCPSubnetHandler interface {
	Handle(UpdateDHCPSubnetParams, interface{}) middleware.Responder
}

// NewUpdateDHCPSubnet creates a new http.Handler for the update d h c p subnet operation
func NewUpdateDHCPSubnet(ctx *middleware.Context, handler UpdateDHCPSubnetHandler) *UpdateDHCPSubnet {
	return &UpdateDHCPSubnet{Context: ctx, Handler: handler}
}

/*
	UpdateDHCPSubnet swagger:route PUT /dhcp/subnet/{subnetId} dhcp updateDHCPSubnet

Updates a DHCPv4 subnet configuration.
*/
type UpdateDHCPSubnet struct {
	Context *middleware.Context
	Handler UpdateDHCPSubnetHandler
}

func (o *UpdateDHCPSubnet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateDHCPSubnetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
