// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/dalet-oss/iris-api/client/dns"
	"github.com/dalet-oss/iris-api/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDNSCreateDNSZoneCmd returns a cmd to handle operation createDnsZone
func makeOperationDNSCreateDNSZoneCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "CreateDNSZone",
		Short: `Creates a new DNS (sub-)zone.`,
		RunE:  runOperationDNSCreateDNSZone,
	}

	if err := registerOperationDNSCreateDNSZoneParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDNSCreateDNSZone uses cmd flags to call endpoint api
func runOperationDNSCreateDNSZone(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dns.NewCreateDNSZoneParams()
	if err, _ := retrieveOperationDNSCreateDNSZoneBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDNSCreateDNSZoneResult(appCli.DNS.CreateDNSZone(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDNSCreateDNSZoneParamFlags registers all flags needed to fill params
func registerOperationDNSCreateDNSZoneParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDNSCreateDNSZoneBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDNSCreateDNSZoneBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelZoneFlags(0, "zone", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationDNSCreateDNSZoneBodyFlag(m *dns.CreateDNSZoneParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.Zone{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.Zone: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.Zone{}
	}
	err, added := retrieveModelZoneFlags(0, bodyValueModel, "zone", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationDNSCreateDNSZoneResult parses request result and return the string content
func parseOperationDNSCreateDNSZoneResult(resp0 *dns.CreateDNSZoneCreated, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dns.CreateDNSZoneCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning createDnsZoneBadRequest is not supported

		// Non schema case: warning createDnsZoneConflict is not supported

		// Non schema case: warning createDnsZoneInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
