// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/dalet-oss/iris-api/client/dhcp"

	"github.com/spf13/cobra"
)

// makeOperationDhcpDisableDHCPCmd returns a cmd to handle operation disableDHCP
func makeOperationDhcpDisableDHCPCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "DisableDHCP",
		Short: `Disable the DHCPv4 service.`,
		RunE:  runOperationDhcpDisableDHCP,
	}

	if err := registerOperationDhcpDisableDHCPParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDhcpDisableDHCP uses cmd flags to call endpoint api
func runOperationDhcpDisableDHCP(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dhcp.NewDisableDHCPParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDhcpDisableDHCPResult(appCli.Dhcp.DisableDHCP(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDhcpDisableDHCPParamFlags registers all flags needed to fill params
func registerOperationDhcpDisableDHCPParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationDhcpDisableDHCPResult parses request result and return the string content
func parseOperationDhcpDisableDHCPResult(resp0 *dhcp.DisableDHCPCreated, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning disableDHCPCreated is not supported

		// Non schema case: warning disableDHCPConflict is not supported

		// Non schema case: warning disableDHCPInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response disableDHCPCreated is not supported by go-swagger cli yet.

	return "", nil
}
