// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/dalet-oss/iris-api/client/dhcp"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDhcpGetDHCPStatusCmd returns a cmd to handle operation getDHCPStatus
func makeOperationDhcpGetDHCPStatusCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetDHCPStatus",
		Short: `Return the status of the DHCPv4 service.`,
		RunE:  runOperationDhcpGetDHCPStatus,
	}

	if err := registerOperationDhcpGetDHCPStatusParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDhcpGetDHCPStatus uses cmd flags to call endpoint api
func runOperationDhcpGetDHCPStatus(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dhcp.NewGetDHCPStatusParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDhcpGetDHCPStatusResult(appCli.Dhcp.GetDHCPStatus(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDhcpGetDHCPStatusParamFlags registers all flags needed to fill params
func registerOperationDhcpGetDHCPStatusParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationDhcpGetDHCPStatusResult parses request result and return the string content
func parseOperationDhcpGetDHCPStatusResult(resp0 *dhcp.GetDHCPStatusOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dhcp.GetDHCPStatusOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
