// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/dalet-oss/iris-api/client/dhcp"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDhcpGetAllDHCPSubnetsCmd returns a cmd to handle operation getAllDHCPSubnets
func makeOperationDhcpGetAllDHCPSubnetsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetAllDHCPSubnets",
		Short: `Returns the IDs of DHCPv4 registered subnets.`,
		RunE:  runOperationDhcpGetAllDHCPSubnets,
	}

	if err := registerOperationDhcpGetAllDHCPSubnetsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDhcpGetAllDHCPSubnets uses cmd flags to call endpoint api
func runOperationDhcpGetAllDHCPSubnets(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dhcp.NewGetAllDHCPSubnetsParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDhcpGetAllDHCPSubnetsResult(appCli.Dhcp.GetAllDHCPSubnets(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDhcpGetAllDHCPSubnetsParamFlags registers all flags needed to fill params
func registerOperationDhcpGetAllDHCPSubnetsParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationDhcpGetAllDHCPSubnetsResult parses request result and return the string content
func parseOperationDhcpGetAllDHCPSubnetsResult(resp0 *dhcp.GetAllDHCPSubnetsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dhcp.GetAllDHCPSubnetsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
