// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/dalet-oss/iris-api/client/dns"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDNSGetDNSZoneRecordCmd returns a cmd to handle operation getDnsZoneRecord
func makeOperationDNSGetDNSZoneRecordCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetDNSZoneRecord",
		Short: `Returns the zone record object.`,
		RunE:  runOperationDNSGetDNSZoneRecord,
	}

	if err := registerOperationDNSGetDNSZoneRecordParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDNSGetDNSZoneRecord uses cmd flags to call endpoint api
func runOperationDNSGetDNSZoneRecord(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dns.NewGetDNSZoneRecordParams()
	if err, _ := retrieveOperationDNSGetDNSZoneRecordRecordIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationDNSGetDNSZoneRecordZoneIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDNSGetDNSZoneRecordResult(appCli.DNS.GetDNSZoneRecord(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDNSGetDNSZoneRecordParamFlags registers all flags needed to fill params
func registerOperationDNSGetDNSZoneRecordParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDNSGetDNSZoneRecordRecordIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationDNSGetDNSZoneRecordZoneIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDNSGetDNSZoneRecordRecordIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	recordIdDescription := `Required. The ID of the DNS record to query.`

	var recordIdFlagName string
	if cmdPrefix == "" {
		recordIdFlagName = "recordId"
	} else {
		recordIdFlagName = fmt.Sprintf("%v.recordId", cmdPrefix)
	}

	var recordIdFlagDefault string

	_ = cmd.PersistentFlags().String(recordIdFlagName, recordIdFlagDefault, recordIdDescription)

	return nil
}
func registerOperationDNSGetDNSZoneRecordZoneIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	zoneIdDescription := `Required. The ID of the DNS zone to query.`

	var zoneIdFlagName string
	if cmdPrefix == "" {
		zoneIdFlagName = "zoneId"
	} else {
		zoneIdFlagName = fmt.Sprintf("%v.zoneId", cmdPrefix)
	}

	var zoneIdFlagDefault string

	_ = cmd.PersistentFlags().String(zoneIdFlagName, zoneIdFlagDefault, zoneIdDescription)

	return nil
}

func retrieveOperationDNSGetDNSZoneRecordRecordIDFlag(m *dns.GetDNSZoneRecordParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("recordId") {

		var recordIdFlagName string
		if cmdPrefix == "" {
			recordIdFlagName = "recordId"
		} else {
			recordIdFlagName = fmt.Sprintf("%v.recordId", cmdPrefix)
		}

		recordIdFlagValue, err := cmd.Flags().GetString(recordIdFlagName)
		if err != nil {
			return err, false
		}
		m.RecordID = recordIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationDNSGetDNSZoneRecordZoneIDFlag(m *dns.GetDNSZoneRecordParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("zoneId") {

		var zoneIdFlagName string
		if cmdPrefix == "" {
			zoneIdFlagName = "zoneId"
		} else {
			zoneIdFlagName = fmt.Sprintf("%v.zoneId", cmdPrefix)
		}

		zoneIdFlagValue, err := cmd.Flags().GetString(zoneIdFlagName)
		if err != nil {
			return err, false
		}
		m.ZoneID = zoneIdFlagValue

	}
	return nil, retAdded
}

// parseOperationDNSGetDNSZoneRecordResult parses request result and return the string content
func parseOperationDNSGetDNSZoneRecordResult(resp0 *dns.GetDNSZoneRecordOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dns.GetDNSZoneRecordOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getDnsZoneRecordNotFound is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
