// Code generated by go-swagger; DO NOT EDIT.

// Package server Iris
//
//	Iris API Server
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 0.2.3
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//	  - text/plain
//
// swagger:meta
package server
