// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Iris API Server",
    "title": "Iris",
    "version": "0.2.4"
  },
  "basePath": "/api/v1",
  "paths": {
    "/dhcp": {
      "get": {
        "description": "Return the status of the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPStatus",
        "responses": {
          "200": {
            "description": "Return the status and version of the DHCPv4 service.",
            "schema": {
              "$ref": "#/definitions/DHCP"
            }
          }
        }
      }
    },
    "/dhcp/disable": {
      "post": {
        "description": "Disable the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DisableDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service has been disabled."
          },
          "409": {
            "description": "The DHCPv4 service was already disable."
          },
          "500": {
            "description": "Unable to disable the DHCPv4 service."
          }
        }
      }
    },
    "/dhcp/enable": {
      "post": {
        "description": "Enable the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "EnableDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service has been enabled."
          },
          "409": {
            "description": "The DHCPv4 service was already enable."
          },
          "500": {
            "description": "Unable to enable the DHCPv4 service."
          }
        }
      }
    },
    "/dhcp/reload": {
      "post": {
        "description": "Reload the DHCPv4 service configuration.",
        "tags": [
          "dhcp"
        ],
        "operationId": "ReloadDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service configuration has been reloaded."
          },
          "500": {
            "description": "Unable to reload the DHCPv4 service configuration."
          }
        }
      }
    },
    "/dhcp/subnet": {
      "get": {
        "description": "Returns the IDs of DHCPv4 registered subnets.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetAllDHCPSubnets",
        "responses": {
          "200": {
            "description": "Returns the an array of DHCPv4 registered subnets.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DHCPv4 subnet.",
        "tags": [
          "dhcp"
        ],
        "operationId": "CreateDHCPSubnet",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Subnet already exists."
          },
          "500": {
            "description": "Unable to create Subnet's resevration."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}": {
      "get": {
        "description": "Returns the requested DHCP Subnet object.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to query.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DHCP Subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DHCPv4 subnet configuration.",
        "tags": [
          "dhcp"
        ],
        "operationId": "UpdateDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet to update.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          },
          "500": {
            "description": "Unable to update subnet."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing subnet.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DeleteDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet to delete.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The subnet has been successfully removed."
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          },
          "409": {
            "description": "The subnet is not empty or still has reservations."
          },
          "500": {
            "description": "Unable to remove the requested subnet."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}/reservation": {
      "get": {
        "description": "Returns the list of MAC hardware addresses of subnet's reservations.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetAllDHCPSubnetReservations",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to get reservations from.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the an array of subnet's reserved MAC addresses.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          }
        }
      },
      "post": {
        "description": "Creates a new DHCPv4 subnet's reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "CreateDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to create reservations on.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created subnet's reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Subnet's reservation already exists."
          },
          "500": {
            "description": "Unable to create Subnet's resevration."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}/reservation/{macID}": {
      "get": {
        "description": "Returns the subnet reservation object.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to query.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to query.",
            "name": "macID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DHCP Reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DHCPv4 subnet reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "UpdateDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet's reservation to update.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to update.",
            "name": "macID",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated Reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          },
          "500": {
            "description": "Unable to update subnet's reservation."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing subnet's reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DeleteDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet's reservation to delete.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to delete.",
            "name": "macID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The reservation has been successfully removed."
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          },
          "500": {
            "description": "Unable to remove the requested reservation."
          }
        }
      }
    },
    "/dns/server": {
      "get": {
        "description": "Returns the IDs of DNS servers.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSServers",
        "responses": {
          "200": {
            "description": "Returns the an array of DNS servers.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "/dns/server/{serverId}": {
      "get": {
        "description": "Returns the requested DNSServer object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSServer",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS server to query.",
            "name": "serverId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNSServer object.",
            "schema": {
              "$ref": "#/definitions/DNSServer"
            }
          },
          "404": {
            "description": "Invalid server ID was provided."
          }
        }
      }
    },
    "/dns/zone": {
      "get": {
        "description": "Returns the IDs of DNS zones.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSZones",
        "responses": {
          "200": {
            "description": "Returns the an array of DNS zones.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DNS (sub-)zone.",
        "tags": [
          "dns"
        ],
        "operationId": "CreateDNSZone",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Zone already exists."
          },
          "500": {
            "description": "Unable to create zone."
          }
        }
      }
    },
    "/dns/zone/{zoneId}": {
      "get": {
        "description": "Returns the requested DNS Zone object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to query.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNS Zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "404": {
            "description": "Invalid zone ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DNS zone configuration.",
        "tags": [
          "dns"
        ],
        "operationId": "UpdateDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone to update.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid zone ID was provided."
          },
          "500": {
            "description": "Unable to update zone."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing zone.",
        "tags": [
          "dns"
        ],
        "operationId": "DeleteDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone to delete.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The zone has been successfully removed."
          },
          "404": {
            "description": "Invalid zone ID was provided."
          },
          "409": {
            "description": "The zone is not empty or still has associated records."
          },
          "500": {
            "description": "Unable to remove the requested zone."
          }
        }
      }
    },
    "/dns/zone/{zoneId}/record": {
      "get": {
        "description": "Returns the list of zone's record IDs.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSZoneRecords",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to get records from.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the an array of zone's record IDs.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Invalid zone ID was provided."
          }
        }
      },
      "post": {
        "description": "Creates a new DNS zone's record.",
        "tags": [
          "dns"
        ],
        "operationId": "CreateDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to create record on.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Record"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created zone's record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Zone's record already exists."
          },
          "500": {
            "description": "Unable to create zone's record."
          }
        }
      }
    },
    "/dns/zone/{zoneId}/record/{recordId}": {
      "get": {
        "description": "Returns the zone record object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to query.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to query.",
            "name": "recordId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNS Record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DNS zone record.",
        "tags": [
          "dns"
        ],
        "operationId": "UpdateDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone's record to update.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to query.",
            "name": "recordId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated Record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          },
          "500": {
            "description": "Unable to update zone's record."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing zone's record.",
        "tags": [
          "dns"
        ],
        "operationId": "DeleteDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone's record to delete.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to delete.",
            "name": "recordId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The DNS record types to be removed.",
            "name": "type",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The record has been successfully removed."
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          },
          "500": {
            "description": "Unable to remove the requested record."
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "Healthz",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "DHCP": {
      "type": "object",
      "properties": {
        "status": {
          "description": "The status of the DHCPv4 service",
          "type": "string",
          "enum": [
            "OK",
            "KO"
          ]
        },
        "version": {
          "description": "The version of the DHCPv4 service",
          "type": "string"
        }
      }
    },
    "DNSServer": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The server ID.",
          "type": "string"
        },
        "type": {
          "description": "The type of DNS server.",
          "type": "string"
        },
        "version": {
          "description": "The version of the DNS server.",
          "type": "string"
        }
      }
    },
    "Record": {
      "type": "object",
      "required": [
        "type",
        "values"
      ],
      "properties": {
        "id": {
          "description": "The DNS record ID.",
          "type": "string"
        },
        "ttl": {
          "description": "The DNS record time-to-live.",
          "type": "number",
          "format": "int32"
        },
        "type": {
          "description": "The DNS record type.",
          "type": "string"
        },
        "values": {
          "description": "The DNS record values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "example": {
        "id": "www.example.com",
        "ttl": 3600,
        "type": "A",
        "values": [
          "192.168.0.1",
          "192.168.0.2"
        ]
      }
    },
    "Reservation": {
      "type": "object",
      "properties": {
        "domain": {
          "description": "The domain name",
          "type": "string"
        },
        "hostname": {
          "description": "The host name",
          "type": "string"
        },
        "ip": {
          "description": "The host IP address.",
          "type": "string"
        },
        "mac": {
          "description": "The host MAC address.",
          "type": "string"
        }
      },
      "example": {
        "domain": "acme.com",
        "hostname": "my-awesome-server",
        "ip": "192.168.0.10",
        "mac": "1a:1b:1c:1d:1e:1f"
      }
    },
    "Subnet": {
      "type": "object",
      "required": [
        "subnet",
        "pools"
      ],
      "properties": {
        "id": {
          "description": "The subnet ID (auto-generated).",
          "type": "string"
        },
        "pools": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubnetPoolRange"
          }
        },
        "subnet": {
          "description": "The subnet in CIDR format (e.g. '192.168.0.0/24').",
          "type": "string"
        }
      }
    },
    "SubnetPoolRange": {
      "type": "object",
      "properties": {
        "first": {
          "description": "The subnet's first IP address for DHCP dynamic leases.",
          "type": "string"
        },
        "last": {
          "description": "The subnet's last IP address for DHCP dynamic leases.",
          "type": "string"
        }
      },
      "example": {
        "first": "192.168.0.51",
        "last": "192.168.0.99"
      }
    },
    "Zone": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "description": "The zone ID.",
          "type": "string"
        },
        "name": {
          "description": "The zone name.",
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Iris API Server",
    "title": "Iris",
    "version": "0.2.4"
  },
  "basePath": "/api/v1",
  "paths": {
    "/dhcp": {
      "get": {
        "description": "Return the status of the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPStatus",
        "responses": {
          "200": {
            "description": "Return the status and version of the DHCPv4 service.",
            "schema": {
              "$ref": "#/definitions/DHCP"
            }
          }
        }
      }
    },
    "/dhcp/disable": {
      "post": {
        "description": "Disable the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DisableDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service has been disabled."
          },
          "409": {
            "description": "The DHCPv4 service was already disable."
          },
          "500": {
            "description": "Unable to disable the DHCPv4 service."
          }
        }
      }
    },
    "/dhcp/enable": {
      "post": {
        "description": "Enable the DHCPv4 service.",
        "tags": [
          "dhcp"
        ],
        "operationId": "EnableDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service has been enabled."
          },
          "409": {
            "description": "The DHCPv4 service was already enable."
          },
          "500": {
            "description": "Unable to enable the DHCPv4 service."
          }
        }
      }
    },
    "/dhcp/reload": {
      "post": {
        "description": "Reload the DHCPv4 service configuration.",
        "tags": [
          "dhcp"
        ],
        "operationId": "ReloadDHCP",
        "responses": {
          "201": {
            "description": "The DHCPv4 service configuration has been reloaded."
          },
          "500": {
            "description": "Unable to reload the DHCPv4 service configuration."
          }
        }
      }
    },
    "/dhcp/subnet": {
      "get": {
        "description": "Returns the IDs of DHCPv4 registered subnets.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetAllDHCPSubnets",
        "responses": {
          "200": {
            "description": "Returns the an array of DHCPv4 registered subnets.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DHCPv4 subnet.",
        "tags": [
          "dhcp"
        ],
        "operationId": "CreateDHCPSubnet",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Subnet already exists."
          },
          "500": {
            "description": "Unable to create Subnet's resevration."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}": {
      "get": {
        "description": "Returns the requested DHCP Subnet object.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to query.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DHCP Subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DHCPv4 subnet configuration.",
        "tags": [
          "dhcp"
        ],
        "operationId": "UpdateDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet to update.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated subnet object.",
            "schema": {
              "$ref": "#/definitions/Subnet"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          },
          "500": {
            "description": "Unable to update subnet."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing subnet.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DeleteDHCPSubnet",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet to delete.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The subnet has been successfully removed."
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          },
          "409": {
            "description": "The subnet is not empty or still has reservations."
          },
          "500": {
            "description": "Unable to remove the requested subnet."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}/reservation": {
      "get": {
        "description": "Returns the list of MAC hardware addresses of subnet's reservations.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetAllDHCPSubnetReservations",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to get reservations from.",
            "name": "subnetId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the an array of subnet's reserved MAC addresses.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Invalid subnet ID was provided."
          }
        }
      },
      "post": {
        "description": "Creates a new DHCPv4 subnet's reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "CreateDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to create reservations on.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created subnet's reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Subnet's reservation already exists."
          },
          "500": {
            "description": "Unable to create Subnet's resevration."
          }
        }
      }
    },
    "/dhcp/subnet/{subnetId}/reservation/{macID}": {
      "get": {
        "description": "Returns the subnet reservation object.",
        "tags": [
          "dhcp"
        ],
        "operationId": "GetDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DHCP subnet to query.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to query.",
            "name": "macID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DHCP Reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DHCPv4 subnet reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "UpdateDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet's reservation to update.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to update.",
            "name": "macID",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated Reservation object.",
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          },
          "500": {
            "description": "Unable to update subnet's reservation."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing subnet's reservation.",
        "tags": [
          "dhcp"
        ],
        "operationId": "DeleteDHCPSubnetReservation",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the subnet's reservation to delete.",
            "name": "subnetId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The hardware MAC address of the reservation to delete.",
            "name": "macID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The reservation has been successfully removed."
          },
          "404": {
            "description": "Invalid subnet ID or reservation MAC address was provided."
          },
          "500": {
            "description": "Unable to remove the requested reservation."
          }
        }
      }
    },
    "/dns/server": {
      "get": {
        "description": "Returns the IDs of DNS servers.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSServers",
        "responses": {
          "200": {
            "description": "Returns the an array of DNS servers.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "/dns/server/{serverId}": {
      "get": {
        "description": "Returns the requested DNSServer object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSServer",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS server to query.",
            "name": "serverId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNSServer object.",
            "schema": {
              "$ref": "#/definitions/DNSServer"
            }
          },
          "404": {
            "description": "Invalid server ID was provided."
          }
        }
      }
    },
    "/dns/zone": {
      "get": {
        "description": "Returns the IDs of DNS zones.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSZones",
        "responses": {
          "200": {
            "description": "Returns the an array of DNS zones.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DNS (sub-)zone.",
        "tags": [
          "dns"
        ],
        "operationId": "CreateDNSZone",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Zone already exists."
          },
          "500": {
            "description": "Unable to create zone."
          }
        }
      }
    },
    "/dns/zone/{zoneId}": {
      "get": {
        "description": "Returns the requested DNS Zone object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to query.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNS Zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "404": {
            "description": "Invalid zone ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DNS zone configuration.",
        "tags": [
          "dns"
        ],
        "operationId": "UpdateDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone to update.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated zone object.",
            "schema": {
              "$ref": "#/definitions/Zone"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid zone ID was provided."
          },
          "500": {
            "description": "Unable to update zone."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing zone.",
        "tags": [
          "dns"
        ],
        "operationId": "DeleteDNSZone",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone to delete.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The zone has been successfully removed."
          },
          "404": {
            "description": "Invalid zone ID was provided."
          },
          "409": {
            "description": "The zone is not empty or still has associated records."
          },
          "500": {
            "description": "Unable to remove the requested zone."
          }
        }
      }
    },
    "/dns/zone/{zoneId}/record": {
      "get": {
        "description": "Returns the list of zone's record IDs.",
        "tags": [
          "dns"
        ],
        "operationId": "GetAllDNSZoneRecords",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to get records from.",
            "name": "zoneId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the an array of zone's record IDs.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Invalid zone ID was provided."
          }
        }
      },
      "post": {
        "description": "Creates a new DNS zone's record.",
        "tags": [
          "dns"
        ],
        "operationId": "CreateDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to create record on.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Record"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the newly created zone's record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "409": {
            "description": "Zone's record already exists."
          },
          "500": {
            "description": "Unable to create zone's record."
          }
        }
      }
    },
    "/dns/zone/{zoneId}/record/{recordId}": {
      "get": {
        "description": "Returns the zone record object.",
        "tags": [
          "dns"
        ],
        "operationId": "GetDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the DNS zone to query.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to query.",
            "name": "recordId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the DNS Record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          }
        }
      },
      "put": {
        "description": "Updates a DNS zone record.",
        "tags": [
          "dns"
        ],
        "operationId": "UpdateDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone's record to update.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to query.",
            "name": "recordId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the updated Record object.",
            "schema": {
              "$ref": "#/definitions/Record"
            }
          },
          "400": {
            "description": "Bad parameters were provided."
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          },
          "500": {
            "description": "Unable to update zone's record."
          }
        }
      },
      "delete": {
        "description": "Deletes an existing zone's record.",
        "tags": [
          "dns"
        ],
        "operationId": "DeleteDNSZoneRecord",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the zone's record to delete.",
            "name": "zoneId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The ID of the DNS record to delete.",
            "name": "recordId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The DNS record types to be removed.",
            "name": "type",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The record has been successfully removed."
          },
          "404": {
            "description": "Invalid zone ID or record ID was provided."
          },
          "500": {
            "description": "Unable to remove the requested record."
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "Healthz",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "DHCP": {
      "type": "object",
      "properties": {
        "status": {
          "description": "The status of the DHCPv4 service",
          "type": "string",
          "enum": [
            "OK",
            "KO"
          ]
        },
        "version": {
          "description": "The version of the DHCPv4 service",
          "type": "string"
        }
      }
    },
    "DNSServer": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The server ID.",
          "type": "string"
        },
        "type": {
          "description": "The type of DNS server.",
          "type": "string"
        },
        "version": {
          "description": "The version of the DNS server.",
          "type": "string"
        }
      }
    },
    "Record": {
      "type": "object",
      "required": [
        "type",
        "values"
      ],
      "properties": {
        "id": {
          "description": "The DNS record ID.",
          "type": "string"
        },
        "ttl": {
          "description": "The DNS record time-to-live.",
          "type": "number",
          "format": "int32"
        },
        "type": {
          "description": "The DNS record type.",
          "type": "string"
        },
        "values": {
          "description": "The DNS record values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "example": {
        "id": "www.example.com",
        "ttl": 3600,
        "type": "A",
        "values": [
          "192.168.0.1",
          "192.168.0.2"
        ]
      }
    },
    "Reservation": {
      "type": "object",
      "properties": {
        "domain": {
          "description": "The domain name",
          "type": "string"
        },
        "hostname": {
          "description": "The host name",
          "type": "string"
        },
        "ip": {
          "description": "The host IP address.",
          "type": "string"
        },
        "mac": {
          "description": "The host MAC address.",
          "type": "string"
        }
      },
      "example": {
        "domain": "acme.com",
        "hostname": "my-awesome-server",
        "ip": "192.168.0.10",
        "mac": "1a:1b:1c:1d:1e:1f"
      }
    },
    "Subnet": {
      "type": "object",
      "required": [
        "subnet",
        "pools"
      ],
      "properties": {
        "id": {
          "description": "The subnet ID (auto-generated).",
          "type": "string"
        },
        "pools": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubnetPoolRange"
          }
        },
        "subnet": {
          "description": "The subnet in CIDR format (e.g. '192.168.0.0/24').",
          "type": "string"
        }
      }
    },
    "SubnetPoolRange": {
      "type": "object",
      "properties": {
        "first": {
          "description": "The subnet's first IP address for DHCP dynamic leases.",
          "type": "string"
        },
        "last": {
          "description": "The subnet's last IP address for DHCP dynamic leases.",
          "type": "string"
        }
      },
      "example": {
        "first": "192.168.0.51",
        "last": "192.168.0.99"
      }
    },
    "Zone": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "description": "The zone ID.",
          "type": "string"
        },
        "name": {
          "description": "The zone name.",
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
}
