// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DNSServer DNS server
//
// swagger:model DNSServer
type DNSServer struct {

	// The server ID.
	ID string `json:"id,omitempty"`

	// The type of DNS server.
	Type string `json:"type,omitempty"`

	// The version of the DNS server.
	Version string `json:"version,omitempty"`
}

// Validate validates this DNS server
func (m *DNSServer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this DNS server based on context it is used
func (m *DNSServer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DNSServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSServer) UnmarshalBinary(b []byte) error {
	var res DNSServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
